CREATE TABLE CARD (
	CARD_ID INT NOT NULL PRIMARY KEY,
	YEAR INT NOT NULL,
	BRAND VARCHAR(50) NOT NULL,
	BRAND_EXT VARCHAR(200),
	CARD_NO INT NOT NULL,
	NAME VARCHAR(200) NOT NULL,
	SPECIAL VARCHAR(200),
	TYPE_CODE INT,
	PRICE DOUBLE,
	FRONT CLOB NOT NULL,
	BACK CLOB NOT NULL
);

CREATE TABLE TYPE_CODE_LKUP (
	TYPE_CODE INT NOT NULL PRIMARY KEY,
	TYPE_DESC VARCAR(100)
);

INSERT INTO TYPE_CODE_LKUP(TYPE_CODE, TYPE_DESC)
	VALUES(1, 'Football');
INSERT INTO TYPE_CODE_LKUP(TYPE_CODE, TYPE_DESC)
	VALUES(2, 'Baseball');
INSERT INTO TYPE_CODE_LKUP(TYPE_CODE, TYPE_DESC)
	VALUES(3, 'Basketball');

CREATE TABLE STOCK(
	STOCK_ID INT NOT NULL PRIMARY KEY,
	CARD_ID INT NOT NULL
);
